# Generated by Django 3.1.1 on 2020-10-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(choices=[('INSO', 'Software Engineering'), ('CIIC', 'Computer Science and Engineering')], default='', max_length=4),
            preserve_default=False,
        ),
    ]
