# Generated by Django 3.1.2 on 2020-10-11 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_user_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycourse',
            name='code',
        ),
        migrations.RemoveField(
            model_name='mycourse',
            name='worth',
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('worth', models.IntegerField()),
                ('pre', models.ManyToManyField(blank=True, related_name='_course_pre_+', to='courses.Course')),
            ],
        ),
        migrations.AddField(
            model_name='mycourse',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='courses.course'),
            preserve_default=False,
        ),
    ]
