# Generated by Django 3.1.2 on 2020-10-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20201011_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
