# Generated by Django 3.1.2 on 2020-10-30 03:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='pre',
        ),
        migrations.AddField(
            model_name='course',
            name='pre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), blank=True, default='{}', size=None),
            preserve_default=False,
        ),
    ]
