# Generated by Django 3.1.2 on 2020-11-07 23:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20201107_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), default='{INSO2015}', size=None),
            preserve_default=False,
        ),
    ]
