# Generated by Django 3.1.2 on 2020-11-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20201107_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='curriculum_year',
            field=models.CharField(choices=[('2015', '2015'), ('2020', '2020')], default='2015', max_length=4),
            preserve_default=False,
        ),
    ]
