# Generated by Django 3.1.2 on 2020-11-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_mycourse_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycourse',
            name='email',
        ),
    ]
